# Generated by Django 5.2.14 on 2026-05-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_licensekey_delete_stripeevent'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant'),
        ),
    ]
