# Generated by Django 5.2.14 on 2026-05-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_license_key_tenant_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
