# Generated by Django 5.2.14 on 2026-05-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gemba', '0001_initial'),
        ('shared', '0003_nullify_dangling_employee_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_assigned_anomalies', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_resolved_anomalies', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_validated_anomalies', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='executionpoint',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_executed_points', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='facetoface',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_f2f_as_manager', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='facetoface',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_f2f_as_operator', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='fivesaudit',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_five_s_audits', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='participants',
            field=models.ManyToManyField(related_name='gemba_tours', through='gemba.TourParticipant', through_fields=('tour', 'user'), to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='tourparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_tour_participations', to='accounts.employee'),
        ),
    ]
