# Generated by Django 5.2.14 on 2026-05-15 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapaTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('capa_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Préventive')], default='corrective', max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identifiée'), ('planned', 'Prévue'), ('in_progress', 'En cours'), ('completed', 'Finalisée'), ('late', 'En retard'), ('validated', 'Validée'), ('archived', 'Archivée')], default='identified', max_length=20)),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=20)),
                ('category_5m', models.CharField(blank=True, choices=[('main_oeuvre', "Main d'œuvre"), ('matiere', 'Matière'), ('methode', 'Méthode'), ('milieu', 'Milieu'), ('machine', 'Machine')], max_length=20, null=True)),
                ('service_id', models.UUIDField(blank=True, null=True)),
                ('line_id', models.UUIDField(blank=True, null=True)),
                ('team_id', models.UUIDField(blank=True, null=True)),
                ('post_id', models.UUIDField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('efficiency_percent', models.IntegerField(blank=True, null=True)),
                ('is_effective', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_piloted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'capa_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
