# Generated by Django 5.2.14 on 2026-05-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('capa', '0001_initial'),
        ('shared', '0003_nullify_dangling_employee_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capaticket',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capa_piloted', to='accounts.employee'),
        ),
    ]
