# Generated by Django 5.2.14 on 2026-05-14 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='trial', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('max_users', models.IntegerField(default=10)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('subscription_ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gemba_active', models.BooleanField(default=False)),
                ('is_audits_active', models.BooleanField(default=False)),
                ('is_iso9001_active', models.BooleanField(default=False)),
                ('is_5s_active', models.BooleanField(default=False)),
                ('is_tpm_active', models.BooleanField(default=False)),
                ('is_lean_flow_active', models.BooleanField(default=False)),
                ('is_vsm_active', models.BooleanField(default=False)),
                ('is_smed_active', models.BooleanField(default=False)),
                ('is_sfm_active', models.BooleanField(default=False)),
                ('is_rotation_active', models.BooleanField(default=False)),
                ('is_capa_active', models.BooleanField(default=False)),
                ('is_risk_active', models.BooleanField(default=False)),
                ('is_problem_solving_active', models.BooleanField(default=False)),
                ('is_poka_yoke_active', models.BooleanField(default=False)),
                ('is_skills_active', models.BooleanField(default=False)),
                ('is_visual_mgmt_active', models.BooleanField(default=False)),
                ('is_routines_active', models.BooleanField(default=False)),
                ('is_messaging_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='core.tenant')),
            ],
            options={
                'db_table': 'core_tenant_licenses',
            },
        ),
    ]
