# Generated by Django 5.2.14 on 2026-05-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_subscription_id',
        ),
    ]
