# Generated by Django 5.2.14 on 2026-05-19 01:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('board_type', models.CharField(choices=[('kanban', 'Kanban'), ('conwip', 'CONWIP'), ('ddmrp', 'DDMRP')], default='kanban', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('wip_limit', models.PositiveIntegerField(default=0, help_text='Global WIP limit for the board (0 = unlimited)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_boards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0, help_text='Display order (0-based)')),
                ('wip_limit', models.PositiveIntegerField(default=0, help_text='Column WIP limit (0 = unlimited)')),
                ('is_done_column', models.BooleanField(default=False, help_text="Mark as the terminal 'Done' column")),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='lean_flow.flowboard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lean_flow_columns', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_columns',
                'ordering': ['board', 'position'],
            },
        ),
        migrations.CreateModel(
            name='FlowCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Bas'), ('medium', 'Moyen'), ('high', 'Eleve'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('position', models.IntegerField(default=0, help_text='Vertical position within the column')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lean_flow_cards', to='accounts.employee')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lean_flow.flowboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lean_flow.flowcolumn')),
            ],
            options={
                'db_table': 'lean_flow_cards',
                'ordering': ['column', 'position'],
            },
        ),
        migrations.CreateModel(
            name='DDMRPBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(help_text='SKU or part reference', max_length=100)),
                ('red_zone', models.PositiveIntegerField(help_text='Threshold below which status is RED', validators=[django.core.validators.MinValueValidator(0)])),
                ('yellow_zone', models.PositiveIntegerField(help_text='Threshold below which status is YELLOW', validators=[django.core.validators.MinValueValidator(0)])),
                ('green_zone', models.PositiveIntegerField(help_text='Upper boundary -- status is GREEN above yellow', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('current_status', models.CharField(choices=[('red', 'Rouge (critique)'), ('yellow', 'Jaune (alerte)'), ('green', 'Vert (nominal)')], default='green', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffers', to='lean_flow.flowboard')),
            ],
            options={
                'db_table': 'lean_flow_ddmrp_buffers',
                'ordering': ['reference'],
                'unique_together': {('board', 'reference')},
            },
        ),
    ]
