# Generated by Django 5.2.14 on 2026-05-19 02:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('lean_flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='adu',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average Daily Usage', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='lead_time_days',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='lt_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Lead time factor (typically 0.5)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='moq',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum Order Quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='ddmrpbuffer',
            name='variability_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Demand variability factor (0.0 - 1.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ddmrpbuffer',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ddmrpbuffer',
            name='green_zone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ddmrpbuffer',
            name='red_zone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ddmrpbuffer',
            name='yellow_zone',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flowboard',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0, help_text='Global WIP limit (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='flowcard',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowcolumn',
            name='is_done_column',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flowcolumn',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowcolumn',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConwipLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('wip_critical', models.PositiveIntegerField(help_text='Max CONWIP tickets allowed in circulation', validators=[django.core.validators.MinValueValidator(1)])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conwip_lines', to='lean_flow.flowboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_conwip_lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConwipLineStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('position', models.PositiveIntegerField(help_text='Order in the sequence (1-based)')),
                ('is_bottleneck', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='lean_flow.conwipline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conwip_stations', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_conwip_stations',
                'ordering': ['line', 'position'],
                'unique_together': {('line', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ConwipTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('free', 'Libre'), ('waiting', 'En attente'), ('in_progress', 'En cours')], default='free', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tickets', to='lean_flow.conwiplinestation')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lean_flow.conwipline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_conwip_tickets',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DDMRPRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recommendation_type', models.CharField(choices=[('replenish', 'Reapprovisionner'), ('accelerate', 'Accelerer production'), ('slow_down', 'Ralentir production'), ('cancel', 'Annuler commande')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('priority', models.IntegerField(default=3, help_text='1=highest, 5=lowest', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvee'), ('executed', 'Executee'), ('rejected', 'Rejetee')], default='pending', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('buffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='lean_flow.ddmrpbuffer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ddmrp_executions', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_ddmrp_recommendations',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanFlowConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(help_text='Article / SKU reference', max_length=100)),
                ('supplier_station', models.CharField(help_text='Upstream workstation name', max_length=150)),
                ('consumer_station', models.CharField(help_text='Downstream workstation name', max_length=150)),
                ('demand_avg', models.DecimalField(decimal_places=2, help_text='Average daily demand (units/day)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lead_time_days', models.DecimalField(decimal_places=2, help_text='Replenishment lead time in days', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('container_capacity', models.PositiveIntegerField(help_text='Units per Kanban card/container', validators=[django.core.validators.MinValueValidator(1)])),
                ('optimal_card_count', models.PositiveIntegerField(default=0, help_text='Auto-calculated on save')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_flows', to='lean_flow.flowboard')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'lean_flow_kanban_configs',
                'ordering': ['reference'],
                'unique_together': {('board', 'reference', 'supplier_station', 'consumer_station')},
            },
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Unique card code (auto-generated)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('full', 'Plein'), ('empty', 'Vide')], default='full', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current quantity in container')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_scans', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lean_flow.kanbanflowconfig')),
            ],
            options={
                'db_table': 'lean_flow_kanban_cards',
                'ordering': ['-last_scanned_at'],
            },
        ),
    ]
