# Generated by Django 5.2.14 on 2026-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, default='', help_text='e.g. certification_expiry · iso_doc_expiry · andon_sla_breach · capa_due', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.UUIDField(blank=True, help_text='UUID of the related object that triggered this notification', null=True),
        ),
    ]
