# Generated by Django 5.2.14 on 2026-05-19 01:00

from django.db import migrations


UPDATED_FKS = [
    ("gemba", "TourParticipant", "user"),
    ("gemba", "ExecutionPoint", "executed_by"),
    ("gemba", "Anomaly", "assigned_to"),
    ("gemba", "Anomaly", "resolved_by"),
    ("gemba", "Anomaly", "validated_by"),
    ("gemba", "FaceToFace", "operator"),
    ("gemba", "FaceToFace", "manager"),
    ("gemba", "FiveSAudit", "auditor"),
    ("audits", "AuditPlan", "responsible"),
    ("audits", "Audit", "lead_auditor"),
    ("audits", "Audit", "auditee"),
    ("audits", "Finding", "assigned_to"),
    ("audits", "Finding", "verified_by"),
    ("capa", "CapaTicket", "pilot"),
    ("problem_solving", "Problem8D", "d2_validated_by"),
    ("problem_solving", "Problem8D", "immediate_actions_validated_by"),
    ("problem_solving", "Problem8D", "rca_validated_by"),
    ("problem_solving", "Problem8D", "final_report_validated_by"),
    ("messaging", "ConversationParticipant", "user"),
]


def nullify_dangling_employee_fks(apps, schema_editor):
    Employee = apps.get_model("accounts", "Employee")
    valid_employee_ids = set(Employee.objects.values_list("id", flat=True))

    for app_label, model_name, field_name in UPDATED_FKS:
        Model = apps.get_model(app_label, model_name)
        field_id = f"{field_name}_id"
        filter_kwargs = {f"{field_id}__isnull": False}
        stale_kwargs = {f"{field_id}__in": valid_employee_ids}

        queryset = Model.objects.filter(**filter_kwargs).exclude(**stale_kwargs)
        queryset.update(**{field_name: None})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gemba', '0001_initial'),
        ('audits', '0001_initial'),
        ('capa', '0001_initial'),
        ('problem_solving', '0001_initial'),
        ('messaging', '0001_initial'),
        ('shared', '0002_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            nullify_dangling_employee_fks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
