# modules/problem_solving/models.py
"""
Problem Solving Module — OPEX SaaS
Combines 8D (from Django legacy) and QRQC (from Node.js legacy) into one module.

Rules:
- All models inherit from BaseModel.
- Operational actors replaced with Employee.
- Notifications routed to shared.models.Notification.
- Actions generated by 8D/QRQC sync to shared.models.Action.
"""
from django.db import models
from shared.base import BaseModel
from accounts.managers import TenantManager


# ─────────────────────────────────────────────────────────────────────
# 8D METHODOLOGY
# ─────────────────────────────────────────────────────────────────────

class Problem8D(BaseModel):
    """
    Formulaire 8D (D0 à D8)
    """
    class Level(models.TextChoices):
        FACTORY  = "factory",  "Usine"
        WORKSHOP = "workshop", "Atelier"
        LINE     = "line",     "Ligne"

    class Step(models.TextChoices):
        D0 = "D0", "D0 - Préparation"
        D1 = "D1", "D1 - Équipe"
        D2 = "D2", "D2 - Description"
        D3 = "D3", "D3 - Sécurisation"
        D4 = "D4", "D4 - Causes Racines"
        D5 = "D5", "D5 - Actions Correctives"
        D6 = "D6", "D6 - Validation"
        D7 = "D7", "D7 - Actions Préventives"
        D8 = "D8", "D8 - Clôture"

    class Status(models.TextChoices):
        OPEN   = "open",   "Ouvert"
        CLOSED = "closed", "Clôturé"

    title        = models.CharField(max_length=255)
    description  = models.TextField(blank=True, help_text="Symptôme initial")
    status       = models.CharField(max_length=20, choices=Status.choices, default=Status.OPEN)
    current_step = models.CharField(max_length=2, choices=Step.choices, default=Step.D0)
    level        = models.CharField(max_length=20, choices=Level.choices)

    # D1
    leader       = models.ForeignKey(
        "accounts.Employee", related_name="led_8d_problems", 
        on_delete=models.SET_NULL, null=True, blank=True
    )
    members      = models.ManyToManyField("accounts.Employee", related_name="involved_8d_problems", blank=True)
    workstation  = models.CharField(max_length=100, blank=True)
    operator_id  = models.CharField(max_length=50, blank=True)
    detection_method  = models.CharField(max_length=255, blank=True)
    impacted_quantity = models.IntegerField(null=True, blank=True)
    importance   = models.TextField(blank=True)
    
    plant         = models.CharField(max_length=100, blank=True)
    workshop_name = models.CharField(max_length=100, blank=True)
    line_name     = models.CharField(max_length=100, blank=True)

    # D2 QQOQCCP
    d2_who       = models.TextField(blank=True)
    d2_what      = models.TextField(blank=True)
    d2_where     = models.TextField(blank=True)
    d2_when      = models.TextField(blank=True)
    d2_how       = models.TextField(blank=True)
    d2_how_many  = models.TextField(blank=True)
    d2_why       = models.TextField(blank=True)
    d2_validated_by = models.ForeignKey(
        "accounts.Employee", related_name="validated_8d_d2",
        null=True, blank=True, on_delete=models.SET_NULL
    )

    # D3
    containment_actions = models.TextField(blank=True)
    process_continue    = models.BooleanField(null=True)
    observations        = models.TextField(blank=True)
    risk_personnel      = models.BooleanField(null=True)
    risk_equipment      = models.BooleanField(null=True)
    non_conformity_type = models.CharField(max_length=255, blank=True)

    immediate_actions_validated_by = models.ForeignKey(
        "accounts.Employee", related_name="validated_8d_d3",
        null=True, blank=True, on_delete=models.SET_NULL
    )
    rca_validated_by = models.ForeignKey(
        "accounts.Employee", related_name="validated_8d_rca",
        null=True, blank=True, on_delete=models.SET_NULL
    )
    final_report_validated_by = models.ForeignKey(
        "accounts.Employee", related_name="validated_8d_final",
        null=True, blank=True, on_delete=models.SET_NULL
    )

    closed_at = models.DateTimeField(null=True, blank=True)

    objects = TenantManager()

    class Meta:
        db_table = "problem_solving_8d"
        ordering = ["-created_at"]

    def __str__(self):
        return f"8D: {self.title} ({self.current_step})"


class RootCause8D(BaseModel):
    class Category(models.TextChoices):
        METHOD      = "method",      "Méthode"
        MACHINE     = "machine",     "Machine"
        MAN         = "man",         "Main d'œuvre"
        MATERIAL    = "material",    "Matière"
        ENVIRONMENT = "environment", "Milieu"
        MEASURE     = "measure",     "Mesure"

    class Method(models.TextChoices):
        FIVE_WHYS = "5P",       "5 Pourquoi"
        ISHIKAWA  = "ishikawa", "Ishikawa"
        OTHER     = "other",    "Autre"

    problem = models.ForeignKey(Problem8D, on_delete=models.CASCADE, related_name="root_causes")
    description = models.TextField()
    details = models.TextField(blank=True)
    category = models.CharField(max_length=20, choices=Category.choices)
    analysis_method = models.CharField(max_length=20, choices=Method.choices, default=Method.FIVE_WHYS)
    other_method = models.CharField(max_length=255, blank=True)
    is_root = models.BooleanField(default=False)
    why_number = models.IntegerField(default=1)

    objects = TenantManager()

    class Meta:
        db_table = "problem_solving_8d_causes"


class Action8D(BaseModel):
    """
    Actions in 8D (Containment, Corrective, Preventive).
    Syncs to shared.models.Action.
    """
    class Type(models.TextChoices):
        CONTAINMENT = "containment", "Confinement (D3)"
        CORRECTIVE  = "corrective",  "Corrective (D5)"
        PREVENTIVE  = "preventive",  "Préventive (D7)"

    class Status(models.TextChoices):
        TODO        = "todo",        "A faire"
        IN_PROGRESS = "in_progress", "En cours"
        DONE        = "done",        "Fait"
        VERIFIED    = "verified",    "Vérifié"

    problem = models.ForeignKey(Problem8D, on_delete=models.CASCADE, related_name="actions")
    root_cause = models.ForeignKey(RootCause8D, on_delete=models.SET_NULL, null=True, blank=True, related_name="actions")
    description = models.TextField()
    action_type = models.CharField(max_length=20, choices=Type.choices)
    assigned_to = models.ForeignKey("accounts.Employee", on_delete=models.SET_NULL, null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.TODO)

    objects = TenantManager()

    class Meta:
        db_table = "problem_solving_8d_actions"

    def sync_to_shared_action(self):
        from shared.models import Action
        status_map = {
            "todo": "open",
            "in_progress": "in_progress",
            "done": "done",
            "verified": "done"
        }
        action, _ = Action.objects.update_or_create(
            reference_id=self.id,
            module_source="8d",
            tenant=self.tenant,
            defaults={
                "title": f"[{self.get_action_type_display()}] {self.problem.title}",
                "description": self.description,
                "status": status_map.get(self.status, "open"),
                "assigned_to": self.assigned_to,
                "due_date": self.due_date,
                "created_by": self.created_by,
                "action_type": self.action_type,
            }
        )
        return action


# ─────────────────────────────────────────────────────────────────────
# QRQC METHODOLOGY (Quick Response Quality Control)
# ─────────────────────────────────────────────────────────────────────

class QRQC(BaseModel):
    """
    Fiche QRQC issue du front-end React.
    """
    class Urgency(models.TextChoices):
        CRITIQUE = "critique", "Critique"
        HAUTE    = "haute",    "Haute"
        MOYENNE  = "moyenne",  "Moyenne"
        BASSE    = "basse",    "Basse"

    class Status(models.TextChoices):
        NOUVEAU  = "nouveau",  "Nouveau"
        EN_COURS = "en_cours", "En cours"
        RESOLU   = "resolu",   "Résolu"
        CLOTURE  = "cloture",  "Clôturé"

    title    = models.CharField(max_length=255)
    problem  = models.TextField(blank=True)
    poste    = models.CharField(max_length=255, blank=True)
    urgency  = models.CharField(max_length=20, choices=Urgency.choices, default=Urgency.MOYENNE)
    status   = models.CharField(max_length=20, choices=Status.choices, default=Status.NOUVEAU)
    cause    = models.TextField(blank=True, help_text="Cause racine identifiée")

    objects = TenantManager()

    class Meta:
        db_table = "problem_solving_qrqc"
        ordering = ["-created_at"]

    def __str__(self):
        return f"QRQC: {self.title} ({self.get_status_display()})"


class QRQCAction(BaseModel):
    """
    Actions rapides pour le QRQC.
    Syncs to shared.models.Action.
    """
    class Status(models.TextChoices):
        A_FAIRE  = "a_faire",  "À faire"
        EN_COURS = "en_cours", "En cours"
        TERMINE  = "termine",  "Terminé"

    qrqc        = models.ForeignKey(QRQC, on_delete=models.CASCADE, related_name="actions")
    description = models.TextField()
    assigned_to = models.ForeignKey("accounts.Employee", on_delete=models.SET_NULL, null=True, blank=True)
    due_date    = models.DateField(null=True, blank=True)
    status      = models.CharField(max_length=20, choices=Status.choices, default=Status.A_FAIRE)

    objects = TenantManager()

    class Meta:
        db_table = "problem_solving_qrqc_actions"

    def sync_to_shared_action(self):
        from shared.models import Action
        status_map = {
            "a_faire": "open",
            "en_cours": "in_progress",
            "termine": "done"
        }
        priority_map = {
            "critique": "critical",
            "haute": "high",
            "moyenne": "medium",
            "basse": "low"
        }
        action, _ = Action.objects.update_or_create(
            reference_id=self.id,
            module_source="qrqc",
            tenant=self.tenant,
            defaults={
                "title": f"[QRQC] {self.qrqc.title}",
                "description": self.description,
                "priority": priority_map.get(self.qrqc.urgency, "medium"),
                "status": status_map.get(self.status, "open"),
                "assigned_to": self.assigned_to,
                "due_date": self.due_date,
                "created_by": self.created_by,
                "action_type": "qrqc_action",
            }
        )
        return action
