# Generated by Django 5.2.14 on 2026-05-21 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('shared', '0003_nullify_dangling_employee_fks'),
        ('tpm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokaYokeDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.CharField(choices=[('physical_fixture', 'Physical fixture'), ('sensor', 'Sensor'), ('barcode_scan', 'Barcode scan'), ('checklist_control', 'Checklist control'), ('software_validation', 'Software validation'), ('visual_control', 'Visual control'), ('interlock', 'Interlock'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('under_review', 'Under review'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('workstation_name', models.CharField(blank=True, max_length=150)),
                ('process_name', models.CharField(blank=True, max_length=150)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('failure_mode', models.TextField(blank=True)),
                ('prevention_method', models.TextField(blank=True)),
                ('detection_method', models.TextField(blank=True)),
                ('automatic_detection', models.BooleanField(default=False)),
                ('standard_reference', models.CharField(blank=True, max_length=150)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('verification_interval_days', models.IntegerField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('next_verification_due', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_devices', to='accounts.department')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_devices', to='tpm.machine')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_devices_owned', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'poka_yoke_devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PokaYokeDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('defect_source', models.CharField(choices=[('device_failed', 'Device failed'), ('device_bypassed', 'Device bypassed'), ('missing_poka_yoke', 'Missing poka-yoke'), ('wrong_standard', 'Wrong standard'), ('human_error', 'Human error'), ('process_drift', 'Process drift'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_defects_detected', to='accounts.employee')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_defects', to='shared.action')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_defects_verified', to='accounts.employee')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='poka_yoke.pokayokedevice')),
            ],
            options={
                'db_table': 'poka_yoke_defects',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='PokaYokeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('measured_value', models.CharField(blank=True, max_length=150)),
                ('expected_value', models.CharField(blank=True, max_length=150)),
                ('requires_action', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_checks', to='accounts.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_checks', to='shared.action')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='poka_yoke.pokayokedevice')),
            ],
            options={
                'db_table': 'poka_yoke_checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PokaYokeImprovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('implemented', 'Implemented'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvements', to='poka_yoke.pokayokedefect')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvements', to='poka_yoke.pokayokedevice')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_improvements', to='shared.action')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_improvements_owned', to='accounts.employee')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poka_yoke_improvements_proposed', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'poka_yoke_improvements',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pokayokedevice',
            index=models.Index(fields=['tenant', 'status'], name='poka_yoke_d_tenant__5b1b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedevice',
            index=models.Index(fields=['tenant', 'device_type'], name='poka_yoke_d_tenant__116349_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedevice',
            index=models.Index(fields=['tenant', 'criticality'], name='poka_yoke_d_tenant__8801da_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedevice',
            index=models.Index(fields=['tenant', 'department'], name='poka_yoke_d_tenant__755ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedevice',
            index=models.Index(fields=['tenant', 'next_verification_due'], name='poka_yoke_d_tenant__9555bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='pokayokedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('tenant', 'code'), name='unique_active_poka_yoke_device_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='pokayokedevice',
            constraint=models.CheckConstraint(condition=models.Q(('verification_interval_days__isnull', True), ('verification_interval_days__gt', 0), _connector='OR'), name='poka_yoke_verification_interval_positive'),
        ),
        migrations.AddIndex(
            model_name='pokayokedefect',
            index=models.Index(fields=['tenant', 'severity'], name='poka_yoke_d_tenant__f3ce23_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedefect',
            index=models.Index(fields=['tenant', 'status'], name='poka_yoke_d_tenant__c13c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedefect',
            index=models.Index(fields=['tenant', 'detected_at'], name='poka_yoke_d_tenant__2c4cee_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokedefect',
            index=models.Index(fields=['tenant', 'defect_source'], name='poka_yoke_d_tenant__97fb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokecheck',
            index=models.Index(fields=['tenant', 'device'], name='poka_yoke_c_tenant__8b711a_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokecheck',
            index=models.Index(fields=['tenant', 'result'], name='poka_yoke_c_tenant__224961_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokecheck',
            index=models.Index(fields=['tenant', 'checked_at'], name='poka_yoke_c_tenant__d00afd_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokecheck',
            index=models.Index(fields=['tenant', 'requires_action'], name='poka_yoke_c_tenant__9e9f08_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeimprovement',
            index=models.Index(fields=['tenant', 'status'], name='poka_yoke_i_tenant__4b01e0_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeimprovement',
            index=models.Index(fields=['tenant', 'priority'], name='poka_yoke_i_tenant__42d0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeimprovement',
            index=models.Index(fields=['tenant', 'due_date'], name='poka_yoke_i_tenant__122f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='pokayokeimprovement',
            index=models.Index(fields=['tenant', 'owner'], name='poka_yoke_i_tenant__83df66_idx'),
        ),
    ]
