# Generated by Django 5.2.14 on 2026-05-19 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VSMMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('current', 'Etat actuel'), ('future', 'Etat futur')], default='current', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('archived', 'Archive')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Prive'), ('department', 'Departement'), ('public', 'Public')], default='private', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('diagram_data', models.JSONField(blank=True, default=dict, help_text='Full diagram payload: {elements: [...], connections: [...]}')),
                ('total_lead_time', models.DecimalField(decimal_places=2, default=0, help_text='Total lead time in seconds', max_digits=12)),
                ('value_added_time', models.DecimalField(decimal_places=2, default=0, help_text='Value-added time in seconds', max_digits=12)),
                ('takt_time', models.DecimalField(decimal_places=2, default=0, help_text='Takt time in seconds', max_digits=12)),
                ('process_count', models.PositiveIntegerField(default=0)),
                ('bottleneck_node_id', models.CharField(blank=True, default='', help_text='ID of the bottleneck process element', max_length=100)),
                ('metrics_json', models.JSONField(blank=True, default=dict, help_text='Full computed metrics: trs, valueAddedRatio, recommendations, etc.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsm_maps', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsm_maps', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'vsm_maps',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VSMElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('element_type', models.CharField(choices=[('supplier', 'Fournisseur'), ('customer', 'Client'), ('process', 'Processus'), ('inventory', 'Stock'), ('transport', 'Transport'), ('information_flow', "Flux d'information"), ('material_flow', 'Flux materiel'), ('kaizen_burst', 'Kaizen')], max_length=30)),
                ('position_x', models.FloatField(default=100)),
                ('position_y', models.FloatField(default=100)),
                ('width', models.FloatField(blank=True, default=150, null=True)),
                ('height', models.FloatField(blank=True, default=100, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Element-specific properties (cycleTime, operators, etc.)')),
                ('connections', models.JSONField(blank=True, default=list, help_text='Array of target element UUIDs this element connects to')),
                ('z_index', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('vsm_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='vsm.vsmmap')),
            ],
            options={
                'db_table': 'vsm_elements',
                'ordering': ['z_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSMVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_num', models.PositiveIntegerField(help_text='Auto-incremented version number')),
                ('label', models.CharField(blank=True, default='', help_text="Optional human-readable label (e.g. 'Before Kaizen Event')", max_length=200)),
                ('diagram_data', models.JSONField(default=dict, help_text='Frozen snapshot of diagram state at version creation time')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen metrics at snapshot time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('vsm_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vsm.vsmmap')),
            ],
            options={
                'db_table': 'vsm_versions',
                'ordering': ['-version_num'],
                'unique_together': {('vsm_map', 'version_num')},
            },
        ),
    ]
