# Generated by Django 5.2.14 on 2026-05-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmmap',
            name='takt_time',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Takt time in seconds', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vsmmap',
            name='total_lead_time',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total lead time in seconds', max_digits=12),
        ),
        migrations.AlterField(
            model_name='vsmmap',
            name='value_added_time',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Value-added time in seconds', max_digits=12),
        ),
    ]
