# Generated by Django 5.2.14 on 2026-05-21 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('shared', '0003_nullify_dangling_employee_fks'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('missed', 'Missed'), ('replaced', 'Replaced')], default='planned', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_assignments', to='accounts.employee')),
                ('replacement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='rotation_table.rotationassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_assignments',
                'ordering': ['plan', 'slot__order', 'workstation__name'],
            },
        ),
        migrations.CreateModel(
            name='RotationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('line', models.CharField(blank=True, max_length=150)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('full_day', 'Full day')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_plans_approved', to='accounts.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('created_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_plans_created', to='accounts.employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_plans', to='accounts.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_plans',
                'ordering': ['-date', 'shift', 'line'],
            },
        ),
        migrations.CreateModel(
            name='RotationIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='rotation_table.rotationassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_incidents', to='shared.action')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_incidents_reported', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='rotation_table.rotationplan')),
            ],
            options={
                'db_table': 'rotation_incidents',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='rotationassignment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rotation_table.rotationplan'),
        ),
        migrations.CreateModel(
            name='RotationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('max_consecutive_same_station', 'Max consecutive same station'), ('required_skill', 'Required skill'), ('avoid_high_risk_repetition', 'Avoid high risk repetition'), ('max_hours_per_station', 'Max hours per station'), ('rest_between_high_risk', 'Rest between high risk')], max_length=50)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocking', 'Blocking')], default='warning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RotationSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='rotation_table.rotationplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_slots',
                'ordering': ['plan', 'order'],
            },
        ),
        migrations.AddField(
            model_name='rotationassignment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rotation_table.rotationslot'),
        ),
        migrations.CreateModel(
            name='RotationViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocking', 'Blocking')], max_length=20)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='rotation_table.rotationassignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_violations', to='shared.action')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='rotation_table.rotationplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_violations_resolved', to='accounts.employee')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='rotation_table.rotationrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_violations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('line', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('required_skill_level', models.IntegerField(default=1)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_workstations', to='accounts.department')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_workstations', to='skills.skill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'rotation_workstations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rotationassignment',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_assignments', to='rotation_table.workstation'),
        ),
        migrations.AddIndex(
            model_name='rotationplan',
            index=models.Index(fields=['tenant', 'date'], name='rotation_pl_tenant__94b801_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationplan',
            index=models.Index(fields=['tenant', 'department', 'date'], name='rotation_pl_tenant__a34657_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationplan',
            index=models.Index(fields=['tenant', 'status'], name='rotation_pl_tenant__364491_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationplan',
            index=models.Index(fields=['tenant', 'shift'], name='rotation_pl_tenant__7ee16e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotationplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'date', 'department', 'line', 'shift'), name='unique_rotation_plan_scope'),
        ),
        migrations.AddIndex(
            model_name='rotationincident',
            index=models.Index(fields=['tenant', 'severity'], name='rotation_in_tenant__56d928_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationincident',
            index=models.Index(fields=['tenant', 'resolved'], name='rotation_in_tenant__a54260_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationincident',
            index=models.Index(fields=['tenant', 'occurred_at'], name='rotation_in_tenant__575381_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationrule',
            index=models.Index(fields=['tenant', 'rule_type'], name='rotation_ru_tenant__d7b950_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationrule',
            index=models.Index(fields=['tenant', 'severity'], name='rotation_ru_tenant__22bcd9_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationrule',
            index=models.Index(fields=['tenant', 'is_enabled'], name='rotation_ru_tenant__392dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationslot',
            index=models.Index(fields=['tenant', 'plan', 'order'], name='rotation_sl_tenant__52d7bd_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationslot',
            index=models.Index(fields=['tenant', 'start_time'], name='rotation_sl_tenant__51b2ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotationslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('plan', 'order'), name='unique_rotation_slot_order_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='rotationslot',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='rotation_slot_order_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rotationslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='rotation_slot_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='rotationviolation',
            index=models.Index(fields=['tenant', 'plan'], name='rotation_vi_tenant__832f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationviolation',
            index=models.Index(fields=['tenant', 'severity'], name='rotation_vi_tenant__b08847_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationviolation',
            index=models.Index(fields=['tenant', 'resolved'], name='rotation_vi_tenant__759551_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['tenant', 'department'], name='rotation_wo_tenant__7c8b69_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['tenant', 'line'], name='rotation_wo_tenant__8d4d55_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['tenant', 'risk_level'], name='rotation_wo_tenant__7c2c38_idx'),
        ),
        migrations.AddIndex(
            model_name='workstation',
            index=models.Index(fields=['tenant', 'is_critical'], name='rotation_wo_tenant__bac4cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('tenant', 'code'), name='unique_active_workstation_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='workstation',
            constraint=models.CheckConstraint(condition=models.Q(('required_skill_level__gte', 1), ('required_skill_level__lte', 4)), name='rotation_workstation_skill_level_range'),
        ),
        migrations.AddIndex(
            model_name='rotationassignment',
            index=models.Index(fields=['tenant', 'plan'], name='rotation_as_tenant__43068c_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationassignment',
            index=models.Index(fields=['tenant', 'slot'], name='rotation_as_tenant__356297_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationassignment',
            index=models.Index(fields=['tenant', 'employee'], name='rotation_as_tenant__80fea9_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationassignment',
            index=models.Index(fields=['tenant', 'workstation'], name='rotation_as_tenant__4545b2_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationassignment',
            index=models.Index(fields=['tenant', 'status'], name='rotation_as_tenant__1d8238_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('tenant', 'slot', 'employee'), name='unique_rotation_employee_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='rotationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('tenant', 'slot', 'workstation'), name='unique_rotation_workstation_per_slot'),
        ),
    ]
