# Generated by Django 5.2.14 on 2026-05-21 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('rotation_table', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rotationplan',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('tenant', 'date', 'line', 'shift'), name='unique_rotation_plan_scope_no_department'),
        ),
    ]
