# Generated by Django 5.2.14 on 2026-05-15 00:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Référence interne (ex: AUD-2026-001)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, help_text='Zone / Département audité', max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('closed', 'Clôturé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Score global 0-100', null=True)),
                ('conclusion', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('auditee', models.ForeignKey(blank=True, help_text='Responsable du processus audité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_as_auditee', to=settings.AUTH_USER_MODEL)),
                ('co_auditors', models.ManyToManyField(blank=True, related_name='audits_as_co', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_as_lead', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'audits_audits',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, help_text='Rubrique / chapitre ISO', max_length=100)),
                ('rating', models.CharField(choices=[('conforme', 'Conforme'), ('observation', 'Observation'), ('non_conforme', 'Non conforme'), ('na', 'Non applicable')], default='na', max_length=20)),
                ('evidence', models.TextField(blank=True, help_text="Preuves / observations de l'auditeur")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='audits/checklist/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='audits.audit')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'audits_checklist_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('one_time', 'Ponctuel'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('semi_annual', 'Semestriel'), ('annual', 'Annuel')], default='one_time', max_length=20)),
                ('year', models.PositiveIntegerField(help_text="Année du programme d'audit")),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_plans_responsible', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'audits_plans',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='audits.auditplan'),
        ),
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('internal', 'Interne'), ('external', 'Externe'), ('supplier', 'Fournisseur'), ('process', 'Processus'), ('system', 'Système')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3788d8', max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'audits_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='auditplan',
            name='audit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='audits.audittype'),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='audits.audittype'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('observation', 'Observation'), ('minor', 'Non-conformité mineure'), ('major', 'Non-conformité majeure'), ('critical', 'Non-conformité critique'), ('improvement', "Piste d'amélioration")], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('action_planned', 'Action planifiée'), ('in_progress', 'En cours de traitement'), ('pending_review', 'En attente de vérification'), ('closed', 'Clôturé')], default='open', max_length=20)),
                ('clause_reference', models.CharField(blank=True, help_text='Référence norme (ex: ISO 9001:2015 §7.1.3)', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='audits/findings/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_assigned', to=settings.AUTH_USER_MODEL)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit')),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='audits.auditchecklistitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('tenant', 'reference'), name='unique_audit_ref_per_tenant'),
        ),
    ]
