# Generated by Django 5.2.14 on 2026-05-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('audits', '0001_initial'),
        ('shared', '0003_nullify_dangling_employee_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='auditee',
            field=models.ForeignKey(blank=True, help_text='Responsable du processus audité', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_as_auditee', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='co_auditors',
            field=models.ManyToManyField(blank=True, related_name='audits_as_co', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='lead_auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_as_lead', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_plans_responsible', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_assigned', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_verified', to='accounts.employee'),
        ),
    ]
