# Generated by Django 5.2.14 on 2026-05-21 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('shared', '0003_nullify_dangling_employee_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SFMSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('line', models.CharField(max_length=150)),
                ('tier_level', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('tier_4', 'Tier 4')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('escalated', 'Escalated'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('meeting_duration_min', models.IntegerField(default=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('facilitated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sfm_sessions_facilitated', to='accounts.employee')),
                ('participants', models.ManyToManyField(blank=True, related_name='sfm_sessions_participated', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'sfm_sessions',
                'ordering': ['-date', 'line', 'tier_level'],
            },
        ),
        migrations.CreateModel(
            name='SFMKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('quality', 'Quality'), ('cost', 'Cost'), ('delivery', 'Delivery'), ('people', 'People'), ('environment', 'Environment')], max_length=20)),
                ('kpi_name', models.CharField(max_length=200)),
                ('objective_description', models.TextField(blank=True)),
                ('target_period', models.DateField(blank=True, null=True)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('trend_logic', models.CharField(choices=[('HIGHER_IS_BETTER', 'Higher is better'), ('LOWER_IS_BETTER', 'Lower is better')], max_length=30)),
                ('color_status', models.CharField(choices=[('GREEN', 'Green'), ('ORANGE', 'Orange'), ('RED', 'Red')], default='GREEN', max_length=10)),
                ('orange_threshold_pct', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('requires_action', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sfm_kpis', to='shared.action')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sfm_kpis_owned', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='sfm.sfmsession')),
            ],
            options={
                'db_table': 'sfm_kpis',
                'ordering': ['session', 'category', 'kpi_name'],
            },
        ),
        migrations.CreateModel(
            name='SFMEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_from_tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('tier_4', 'Tier 4')], max_length=20)),
                ('escalated_to_tier', models.CharField(choices=[('tier_1', 'Tier 1'), ('tier_2', 'Tier 2'), ('tier_3', 'Tier 3'), ('tier_4', 'Tier 4')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sfm_escalations_created', to='accounts.employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sfm_escalations_resolved', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sfm.sfmkpi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='sfm.sfmsession')),
            ],
            options={
                'db_table': 'sfm_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sfmsession',
            index=models.Index(fields=['tenant', 'date'], name='sfm_session_tenant__b36c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmsession',
            index=models.Index(fields=['tenant', 'line', 'date'], name='sfm_session_tenant__5605e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmsession',
            index=models.Index(fields=['tenant', 'status'], name='sfm_session_tenant__c0bcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmsession',
            index=models.Index(fields=['tenant', 'tier_level'], name='sfm_session_tenant__8e5d83_idx'),
        ),
        migrations.AddConstraint(
            model_name='sfmsession',
            constraint=models.UniqueConstraint(fields=('tenant', 'line', 'date', 'tier_level'), name='unique_sfm_session_per_line_date_tier'),
        ),
        migrations.AddConstraint(
            model_name='sfmsession',
            constraint=models.CheckConstraint(condition=models.Q(('meeting_duration_min__gt', 0)), name='sfm_session_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='sfmkpi',
            index=models.Index(fields=['tenant', 'session', 'category'], name='sfm_kpis_tenant__09f60a_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmkpi',
            index=models.Index(fields=['tenant', 'color_status'], name='sfm_kpis_tenant__ee0992_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmkpi',
            index=models.Index(fields=['tenant', 'category'], name='sfm_kpis_tenant__42be5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sfmkpi',
            constraint=models.CheckConstraint(condition=models.Q(('target__gte', 0)), name='sfm_kpi_target_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sfmkpi',
            constraint=models.CheckConstraint(condition=models.Q(('actual__gte', 0)), name='sfm_kpi_actual_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sfmkpi',
            constraint=models.CheckConstraint(condition=models.Q(('orange_threshold_pct__gt', 0), ('orange_threshold_pct__lte', 100)), name='sfm_kpi_orange_threshold_range'),
        ),
        migrations.AddIndex(
            model_name='sfmescalation',
            index=models.Index(fields=['tenant', 'status'], name='sfm_escalat_tenant__65360f_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmescalation',
            index=models.Index(fields=['tenant', 'escalated_to_tier'], name='sfm_escalat_tenant__5389da_idx'),
        ),
        migrations.AddIndex(
            model_name='sfmescalation',
            index=models.Index(fields=['tenant', 'session'], name='sfm_escalat_tenant__40f58e_idx'),
        ),
    ]
