# Generated by Django 5.2.14 on 2026-05-21 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('tpm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_before', models.CharField(max_length=150)),
                ('product_after', models.CharField(max_length=150)),
                ('date_observed', models.DateField()),
                ('status', models.CharField(choices=[('observation', 'Observation'), ('analysis', 'Analysis'), ('optimised', 'Optimised')], default='observation', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_time_before', models.IntegerField(default=0)),
                ('total_time_after', models.IntegerField(default=0)),
                ('internal_time_before', models.IntegerField(default=0)),
                ('internal_time_after', models.IntegerField(default=0)),
                ('improvement_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('externalisation_gain_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smed_sessions', to='tpm.machine')),
                ('observed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smed_sessions_observed', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smed_sessions_validated', to='accounts.employee')),
            ],
            options={
                'db_table': 'smed_sessions',
                'ordering': ['-date_observed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMEDStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('step_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('duration_before_sec', models.IntegerField(default=0)),
                ('duration_after_sec', models.IntegerField(default=0)),
                ('can_externalise', models.BooleanField(default=False)),
                ('is_optimised', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smed_steps_operated', to='accounts.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='smed.smedsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'smed_steps',
                'ordering': ['session', 'order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'status'], name='smed_sessio_tenant__91f745_idx'),
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'date_observed'], name='smed_sessio_tenant__ae6f2e_idx'),
        ),
        migrations.AddIndex(
            model_name='smedstep',
            index=models.Index(fields=['tenant', 'session', 'order'], name='smed_steps_tenant__be2753_idx'),
        ),
        migrations.AddIndex(
            model_name='smedstep',
            index=models.Index(fields=['tenant', 'step_type'], name='smed_steps_tenant__0eada2_idx'),
        ),
    ]
