# Generated by Django 5.2.14 on 2026-05-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('smed', '0001_initial'),
        ('tpm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smedsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smedsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smed_sessions_approved', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='smedsession',
            name='external_time_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smedsession',
            name='external_time_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smedsession',
            name='locked_for_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'machine', 'date_observed'], name='smed_sessio_tenant__fb56b1_idx'),
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'status', 'date_observed'], name='smed_sessio_tenant__d16b24_idx'),
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'observed_by'], name='smed_sessio_tenant__bbfaca_idx'),
        ),
        migrations.AddIndex(
            model_name='smedsession',
            index=models.Index(fields=['tenant', 'validated_by'], name='smed_sessio_tenant__bf6e27_idx'),
        ),
        migrations.AddConstraint(
            model_name='smedsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_time_before__gte', 0)), name='smed_session_total_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='smedsession',
            constraint=models.CheckConstraint(condition=models.Q(('total_time_after__gte', 0)), name='smed_session_total_after_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='smedstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('session', 'order'), name='unique_smed_step_order_per_session'),
        ),
        migrations.AddConstraint(
            model_name='smedstep',
            constraint=models.CheckConstraint(condition=models.Q(('duration_before_sec__gte', 0)), name='smed_step_duration_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='smedstep',
            constraint=models.CheckConstraint(condition=models.Q(('duration_after_sec__gte', 0)), name='smed_step_duration_after_nonnegative'),
        ),
    ]
