# Generated by Django 5.2.14 on 2026-05-15 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem8D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Symptôme initial')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé')], default='open', max_length=20)),
                ('current_step', models.CharField(choices=[('D0', 'D0 - Préparation'), ('D1', 'D1 - Équipe'), ('D2', 'D2 - Description'), ('D3', 'D3 - Sécurisation'), ('D4', 'D4 - Causes Racines'), ('D5', 'D5 - Actions Correctives'), ('D6', 'D6 - Validation'), ('D7', 'D7 - Actions Préventives'), ('D8', 'D8 - Clôture')], default='D0', max_length=2)),
                ('level', models.CharField(choices=[('factory', 'Usine'), ('workshop', 'Atelier'), ('line', 'Ligne')], max_length=20)),
                ('workstation', models.CharField(blank=True, max_length=100)),
                ('operator_id', models.CharField(blank=True, max_length=50)),
                ('detection_method', models.CharField(blank=True, max_length=255)),
                ('impacted_quantity', models.IntegerField(blank=True, null=True)),
                ('importance', models.TextField(blank=True)),
                ('plant', models.CharField(blank=True, max_length=100)),
                ('workshop_name', models.CharField(blank=True, max_length=100)),
                ('line_name', models.CharField(blank=True, max_length=100)),
                ('d2_who', models.TextField(blank=True)),
                ('d2_what', models.TextField(blank=True)),
                ('d2_where', models.TextField(blank=True)),
                ('d2_when', models.TextField(blank=True)),
                ('d2_how', models.TextField(blank=True)),
                ('d2_how_many', models.TextField(blank=True)),
                ('d2_why', models.TextField(blank=True)),
                ('containment_actions', models.TextField(blank=True)),
                ('process_continue', models.BooleanField(null=True)),
                ('observations', models.TextField(blank=True)),
                ('risk_personnel', models.BooleanField(null=True)),
                ('risk_equipment', models.BooleanField(null=True)),
                ('non_conformity_type', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d2_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_d2', to=settings.AUTH_USER_MODEL)),
                ('final_report_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_final', to=settings.AUTH_USER_MODEL)),
                ('immediate_actions_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_d3', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_8d_problems', to='accounts.employee')),
                ('members', models.ManyToManyField(blank=True, related_name='involved_8d_problems', to='accounts.employee')),
                ('rca_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_rca', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'problem_solving_8d',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRQC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField(blank=True)),
                ('poste', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé')], default='nouveau', max_length=20)),
                ('cause', models.TextField(blank=True, help_text='Cause racine identifiée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'problem_solving_qrqc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRQCAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('qrqc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='problem_solving.qrqc')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'problem_solving_qrqc_actions',
            },
        ),
        migrations.CreateModel(
            name='RootCause8D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('method', 'Méthode'), ('machine', 'Machine'), ('man', "Main d'œuvre"), ('material', 'Matière'), ('environment', 'Milieu'), ('measure', 'Mesure')], max_length=20)),
                ('analysis_method', models.CharField(choices=[('5P', '5 Pourquoi'), ('ishikawa', 'Ishikawa'), ('other', 'Autre')], default='5P', max_length=20)),
                ('other_method', models.CharField(blank=True, max_length=255)),
                ('is_root', models.BooleanField(default=False)),
                ('why_number', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='problem_solving.problem8d')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'problem_solving_8d_causes',
            },
        ),
        migrations.CreateModel(
            name='Action8D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('containment', 'Confinement (D3)'), ('corrective', 'Corrective (D5)'), ('preventive', 'Préventive (D7)')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'A faire'), ('in_progress', 'En cours'), ('done', 'Fait'), ('verified', 'Vérifié')], default='todo', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='problem_solving.problem8d')),
                ('root_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='problem_solving.rootcause8d')),
            ],
            options={
                'db_table': 'problem_solving_8d_actions',
            },
        ),
    ]
