# Generated by Django 5.2.14 on 2026-05-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('problem_solving', '0001_initial'),
        ('shared', '0003_nullify_dangling_employee_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem8d',
            name='d2_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_d2', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='problem8d',
            name='final_report_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_final', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='problem8d',
            name='immediate_actions_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_d3', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='problem8d',
            name='rca_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_8d_rca', to='accounts.employee'),
        ),
    ]
