# Generated by Django 5.2.14 on 2026-05-21 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_remove_tenant_stripe_customer_id_and_more'),
        ('shared', '0003_nullify_dangling_employee_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('full_day', 'Full day'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('global_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial'), ('not_applicable', 'Not applicable')], default='not_applicable', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validator_comment', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_executions', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_executions_validated', to='accounts.employee')),
            ],
            options={
                'db_table': 'routine_executions',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('yes_no', 'Yes/no'), ('numeric', 'Numeric'), ('text', 'Text'), ('photo_required', 'Photo required'), ('signature', 'Signature'), ('checklist', 'Checklist')], default='yes_no', max_length=20)),
                ('expected_value', models.CharField(blank=True, max_length=150)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('order', models.IntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('triggers_action_on_fail', models.BooleanField(default=True)),
                ('is_ok_demarrage', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'routine_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineStepResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_applicable', 'Not applicable')], max_length=20)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='routines.routineexecution')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_step_responses', to='shared.action')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_step_responses', to='accounts.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='routines.routinestep')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'routine_step_responses',
                'ordering': ['step__order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_deviations_detected', to='accounts.employee')),
                ('linked_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_deviations', to='shared.action')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_deviations_owned', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_deviations_verified', to='accounts.employee')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='routines.routineexecution')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='routines.routinestepresponse')),
            ],
            options={
                'db_table': 'routine_deviations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('routine_type', models.CharField(choices=[('daily_startup', 'Daily startup'), ('ok_demarrage', 'OK demarrage'), ('safety_walk', 'Safety walk'), ('quality_check', 'Quality check'), ('maintenance_check', 'Maintenance check'), ('supervisor_routine', 'Supervisor routine'), ('other', 'Other')], default='other', max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_shift', 'Per shift'), ('ad_hoc', 'Ad hoc')], max_length=20)),
                ('line', models.CharField(blank=True, max_length=150)),
                ('workstation_name', models.CharField(blank=True, max_length=150)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('estimated_duration_min', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.CharField(choices=[('v1.0', 'v1.0'), ('v1.1', 'v1.1'), ('v2.0', 'v2.0')], default='v1.0', max_length=10)),
                ('requires_validation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_templates', to='accounts.department')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_templates_owned', to='accounts.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'routine_templates',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='routinestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routines.routinetemplate'),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='routines.routinetemplate'),
        ),
        migrations.AddIndex(
            model_name='routinestepresponse',
            index=models.Index(fields=['tenant', 'execution'], name='routine_ste_tenant__fd9970_idx'),
        ),
        migrations.AddIndex(
            model_name='routinestepresponse',
            index=models.Index(fields=['tenant', 'step'], name='routine_ste_tenant__c433de_idx'),
        ),
        migrations.AddIndex(
            model_name='routinestepresponse',
            index=models.Index(fields=['tenant', 'result'], name='routine_ste_tenant__ef90d7_idx'),
        ),
        migrations.AddIndex(
            model_name='routinestepresponse',
            index=models.Index(fields=['tenant', 'responded_at'], name='routine_ste_tenant__f0cfcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinestepresponse',
            constraint=models.UniqueConstraint(fields=('execution', 'step'), name='unique_routine_response_per_step'),
        ),
        migrations.AddIndex(
            model_name='routinedeviation',
            index=models.Index(fields=['tenant', 'severity'], name='routine_dev_tenant__01e052_idx'),
        ),
        migrations.AddIndex(
            model_name='routinedeviation',
            index=models.Index(fields=['tenant', 'status'], name='routine_dev_tenant__a36ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='routinedeviation',
            index=models.Index(fields=['tenant', 'owner'], name='routine_dev_tenant__484df3_idx'),
        ),
        migrations.AddIndex(
            model_name='routinedeviation',
            index=models.Index(fields=['tenant', 'due_date'], name='routine_dev_tenant__66f1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='routinetemplate',
            index=models.Index(fields=['tenant', 'status'], name='routine_tem_tenant__908b51_idx'),
        ),
        migrations.AddIndex(
            model_name='routinetemplate',
            index=models.Index(fields=['tenant', 'routine_type'], name='routine_tem_tenant__345db0_idx'),
        ),
        migrations.AddIndex(
            model_name='routinetemplate',
            index=models.Index(fields=['tenant', 'frequency'], name='routine_tem_tenant__b1c30b_idx'),
        ),
        migrations.AddIndex(
            model_name='routinetemplate',
            index=models.Index(fields=['tenant', 'department'], name='routine_tem_tenant__48e68c_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), models.Q(('code', ''), _negated=True)), fields=('tenant', 'code'), name='unique_active_routine_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='routinetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_duration_min__gt', 0)), name='routine_template_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='routinestep',
            index=models.Index(fields=['tenant', 'template', 'order'], name='routine_ste_tenant__4aba65_idx'),
        ),
        migrations.AddIndex(
            model_name='routinestep',
            index=models.Index(fields=['tenant', 'step_type'], name='routine_ste_tenant__5e26e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='routinestep',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_routine_step_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='routinestep',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='routine_step_order_non_negative'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['tenant', 'scheduled_for'], name='routine_exe_tenant__e911cc_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['tenant', 'status'], name='routine_exe_tenant__fa4684_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['tenant', 'executed_by'], name='routine_exe_tenant__3e03cc_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexecution',
            index=models.Index(fields=['tenant', 'template'], name='routine_exe_tenant__2b161a_idx'),
        ),
    ]
